[package]
name = "liboneshot-3d-nativetools"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging", ] }
